### ISSUE TITLE
Add a utility for parsing dates

### ISSUE THREAD

**Issue by aramperes** [wavy/wavyfm-python#5]
The wavy.fm API uses the RFC3339 date format. It's [not well supported in Python](https://stackoverflow.com/questions/1941927/convert-an-rfc-3339-time-to-a-standard-python-timestamp), so it would be nice to have a public utility to parse dates (without requiring an external dependency).

Example date: `2020-05-18T06:54:14.188Z`. It's basically ISO-8601 but with  `Z` (UTC timezone) added at the end.

**Comment by jakeledoux** [comment]
Are you just looking to get a datetime object? If so you can just use the strptime method.
``` python3
from datetime import datetime


def datetime_from_string(raw_date: str) -> datetime:
    """ Creates a UTC DateTime object from a RFC3339 formatted string.
    """
    return datetime.strptime(raw_date, '%Y-%m-%dT%H:%M:%S.%f%z')
```

**Comment by aramperes** [comment]
Yes, precisely. It'd be nice to include this in the library because the built-in 'fromisotimestamp' doesn't like the Zulu suffix, and so that apps don't have to reimplement it.
